FROM osgeo/gdal:ubuntu-small-3.5.0 AS build
RUN apt update; apt install -y python3-pip
RUN rm -rf /usr/lib/python3/dist-packages/numpy*

COPY ./requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./dist/*.whl .
RUN pip3 install *.whl

FROM osgeo/gdal:ubuntu-small-3.5.0
RUN rm -rf /usr/lib/python3/dist-packages/numpy*
WORKDIR /app
RUN apt install -y gunicorn
COPY ./app.py ./app.py
COPY ./pyproject.toml ./pyproject.toml
COPY --from=build /usr/local/lib/python3.8/dist-packages/ /usr/local/lib/python3.8/dist-packages/
CMD exec gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 app:app
