FROM osgeo/gdal:ubuntu-small-latest AS build
RUN apt update; apt install -y python3-pip

COPY ./requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./dist/*.whl .
RUN pip3 install *.whl

FROM osgeo/gdal:ubuntu-small-latest
WORKDIR /app
COPY ./app.py ./app.py
COPY --from=build /usr/local/lib/python3.8/dist-packages/ /usr/local/lib/python3.8/dist-packages/
CMD exec gunicorn --bind :$PORT --workers 1 --threads --timeout 0 app:app
