name: Pytest CI

on:
  push
  
jobs:
  test:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up GIS dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt update
        sudo apt install libspatialindex-dev gdal-bin

    - name: Install dependencies
      run: |
        cd backend
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
        poetry install
        
    - name: Run Tests
      run: |
        cd backend
        poetry run pytest .
