name: Build

on:
  push:
    branches:
      - build

env:
  GOOGLE_CLOUD_REGION: "australia-southeast2"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Install system dependencies
      run: |
        sudo apt install jq
    
    - name: Generate python wheel and dependencies
      run: |
        cd backend
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
        poetry build -f wheel
        poetry export -f requirements.txt -E docker --output requirements.txt
        
    - name: Build Docker image
      run: |
        cd backend
        docker build -t ${{ steps.images.outputs.DOCKERHUB_LATEST }}
    
    - name: Set image names
      id: images
      run: |
        PROJECT_ID=$(cat ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} | jq '.project_id')
        echo "::set-output name=DOCKERHUB_LATEST::'btang164/running-routes:latest'
        echo "::set-output name=DOCKERHUB_SHA::'btang164/running-routes:${github.sha::7}'"
        echo "::set-output name=GOOGLE_LATEST::'https://${env.GOOGLE_CLOUD_REGION}-docker.pkg.dev${PROJECT_ID}/btang164/running-routes:latest'"

    - name: Push image to DockerHub
      run: |
        cat ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u btang164 --password-stdin
        docker tag ${{ steps.images.outputs.DOCKERHUB_LATEST }} ${{ steps.images.outputs.DOKERHUB_SHA }}
        docker push ${{ steps.images.output.DOCKERHUB_LATEST }} 
        docker push ${{ steps.images.output.DOCKERHUB_SHA }} 
      
    - name: Push image to Google Artifact Registry
      run: |
        cat ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin "https://${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev"
        docker tag ${{ steps.images.outputs.DOCKERHUB_LATEST }} ${{ steps.images.outputs.GOOGLE_LATEST }}
        docker push ${{ steps.images.outputs.GOOGLE_LATEST }}
